version: "3.3"

services:
  node:
    container_name: autoparts_backend
    restart: always
    image: node:16.10.0
    ports:
      - 3006:3006
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app

    networks:
      - autoparts_backend

    # PRODUCTION
    command: bash -c "npm install && npm run start:prod"

    # DEVELOPMENT
    # command: bash -c "npm install && npm run dev"

networks:
  viserpet_network:
    driver: bridge
