version: "1.1"

services:
  node:
    container_name: autoparts_backend
    restart: always
    image: node:16.10.0
    ports:
      - 3006:3006
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app

    networks:
      - autoparts_network

    #PRODUCTION
    command: bash -c "npm install && npm run start:prod"

networks:
  autoparts_network:
    driver: bridge
